### ISSUE TITLE
example: bitcoin blockchain

### ISSUE THREAD

**Issue by ralphtheninja** [dominictarr/cyphernet#9]
Cypherlinks can be links to any kind of blobs and doesn't necessarily have to be human readable documents such as blog posts.

A blob might as well be a block in the bitcoin blockchain, which essentially is just a single linked list where each item in the list contains transaction data and a pointer back (which is the hash of that block) to the previous item in the list.

Each transaction is also identified with a hash, which turns the single linked list into a tree where one leaf is the latest block in the chain and the rest of the leaves are transactions. So the core blockchain can be looked at as the stem of a tree, with the genesis block as the root. Or perhaps more like a bean stalk growing up into the sky :)

Naturally this can be used for any type of crypto currency using a similar system and not just bitcoin, for example litecoin or feathercoin.

**Comment by dominictarr** [comment]
Absolutely!

This also raises an interesting case, because bitcoin uses a binary format, so you need to detect some how what the blob represents.

You can also put messages into transactions, which can be cypherlinks to other objects.
This is actually very interesting, because it's so computational hard to create new blocks,
if you create a hash and put it into the block chain (say, by making a small transaction)
you have proven that it really was created at approximately at that time, because it would be impossible to calculate the blocks in front of it, in less time.

**Comment by ralphtheninja** [comment]
Yep. That's why Satoshi put the text "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks" into the genesis block to indicate that the block couldn't have been created before that day.

https://en.bitcoin.it/wiki/Genesis_block

Hmm. Since a block has a certain structure you could look at it as a binary file format. Perhaps you could create a new content type for this type of data? Assuming you have extracted the hash from another block, you always know that the corresponding blob is another block.

**Comment by ralphtheninja** [comment]
When you store a block you could create meta data pointing to the block - which is a cypherlink of course - that contains the content type. It would be really nice if there was a good mechanism for doing reverse lookup from a hash to its meta data. Then it's cake to find out what type of data the blob represents.

**Comment by dominictarr** [comment]
It's easy to make a proof that something came _after_ something else, the message in the genesis block indicates it came after that headline.

But I am saying that you can do it the other way around,
If you put a hash inside a transaction, then wait an hour.
now, anyone else can be pretty confidant that it really was created an hour ago,
because of the incredible cost of generating 6 valid blocks, within, say 10 minutes.

Ideally, you would detect the structure of a blob, and recognise it as a bitcoin transaction.

yes, it's easy to attach metadata via a link. All links in blobs you have locally will be indexed
so that they can be efficiently traversed/queried. As in github.com/dominictarr/level-search

**Comment by ralphtheninja** [comment]
That's a very good point! This actually makes bitcoin nodes more useful, they serve another purpose than "just" doing a lot of hash calculations per second. It's almost like carving something into a very hard material with some super diamond, it takes a lot of work to change or delete the information.
